name: "${artifactId}"
author: "${author}"
main: "${mainClass}"
version: "${version}"

api-version: 1.13

commands:
  backpack:
    usage: "Usage: /<command>"
    description: "Opens a shared backpack."
    permission: backpack.open
    aliases: [bp]

permissions:
  backpack.open:
    description: "Allows a player to open a shared backpack"
    default: op